language: node_js
node_js:
  - "9"
dist: trusty
sudo: false
branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test:unit
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master