language: node_js
node_js:
  - 12
dist: trusty
os: linux

branches:
  only:
  - master

cache:
  npm: false
  directories:
    - node_modules

script:
  - set -e
  - npm run lint
  - npm run test:unit
  - npm run build

after_script:
  - cat ./coverage/lcov.info | coveralls

deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: dist
  token: $GITHUB_TOKEN
  on:
    branch: master